name: Data Pipeline

on:
    push:
        branches:
        - main
    # schedule:
    #     - cron: '0 0 * * 0'      

jobs:
  download-and-populate-db:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Data
      run: |
        curl -L 'URL_TO_ZIP_FILE' -o data.zip

    - name: Unzip Data
      run: |
        unzip data.zip -d data

    - name: Populate MongoDB Database
      env:
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      run: |
        python populate_db.py
