name: Data Pipeline

on:
    push:
        branches:
        - main
    schedule:
        - cron: '0 0 * * 0'      

jobs:
  data_import:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the data processing script
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DB_NAME: ${{ secrets.DB_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
        WEB_LOGIN: ${{ secrets.WEB_USERNAME }}  
        WEB_PASSWORD: ${{ secrets.WEB_PASSWORD }}  
      run: python populateData.py        